# CodeRabbit configuration for AutoMem
# Docs: https://docs.coderabbit.ai/reference/configuration

language: en-US

reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false  # Don't review draft PRs

  profile: chill  # Less verbose, focuses on real issues

  request_changes_workflow: false  # Comment only, don't block

  path_instructions:
    - path: "automem/**/*.py"
      instructions: |
        - Ensure graph writes always succeed even if vector storage fails (graceful degradation)
        - Verify all timestamps are normalized to UTC ISO format
        - Check that graph operations are atomic with automatic rollback on errors
        - Log vector store errors but don't block graph writes
        - Use type hints consistently
        - Follow Black formatting (100 char line length)

    - path: "mcp-sse-server/**/*.js"
      instructions: |
        - Verify ES6 exports match what tests import (AutoMemClient, createApp, formatRecallAsItems)
        - Check all /recall API parameters are forwarded through the MCP bridge
        - Ensure Express middleware order is correct

    - path: "tests/**/*.py"
      instructions: |
        - Use pytest fixtures instead of global variables
        - Ensure compatibility with PYTEST_DISABLE_PLUGIN_AUTOLOAD=1
        - Use DummyGraph fixture to mock FalkorDB operations

    - path: "**/*.md"
      instructions: |
        - Check that API documentation matches actual implementation
        - Verify code examples are syntactically correct

  tools:
    ruff:
      enabled: true
    eslint:
      enabled: true

knowledge_base:
  learnings:
    scope: auto  # Learn from this repo's patterns
