# docker-compose.yml - Local development environment

services:
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379"  # Redis/FalkorDB
      - "3000:3000"  # Browser UI
    volumes:
      - falkordb_data:/var/lib/falkordb/data
    environment:
      - REDIS_ARGS=--save 60 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.11.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  flask-api:
    build: .
    ports:
      - "8001:8001"  # Flask API
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      PORT: 8001
      FALKORDB_HOST: falkordb
      QDRANT_URL: http://qdrant:6333
      QDRANT_API_KEY: ${QDRANT_API_KEY:-}
      AUTOMEM_API_TOKEN: ${AUTOMEM_API_TOKEN:-test-token}
      ADMIN_API_TOKEN: ${ADMIN_API_TOKEN:-test-admin-token}
    depends_on:
      falkordb:
        condition: service_healthy
      qdrant:
        condition: service_started
    volumes:
      - .:/app

volumes:
  falkordb_data:
  qdrant_data:
